Repository CruGlobal/ab_runtime, pull requests merged in 2024-03, with the labels that each got.

#367 Ci/staging/2.1.11
  package-lock.json
  package.json
  version.json
Labels: patch

#369 Add a new command for working with DataCollection cursors
  test/e2e/cypress/support/commands.js
Labels: patch

#373 block outgoing sentry requests from cypress tests
  test/e2e/cypress/support/e2e.js
Labels: skip-release

#366 Switcheroo Test
  package-lock.json
  package.json
  test/e2e/cypress/e2e/0002_portal_work.cy.js
Labels: skip-release

#371 Add new Testing Tools
  test/e2e/cypress.config.mjs
  test/e2e/cypress/support/commands.js
  test/e2e/cypress/support/e2e.js
Labels: enhancement, minor
